<a href="https://colab.research.google.com/github/ShawnTayNWU/MSDS460/blob/Assignments/Final_Project_HistStockPriceToCSV_Anu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install yfinance

Collecting yfinance
  Downloading yfinance-0.1.70-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.21.5)
Collecting lxml>=4.5.1
  Downloading lxml-4.8.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (6.4 MB)
     |████████████████████████████████| 6.4 MB 17.7 MB/s
Collecting requests>=2.26
  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 788 kB/s
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from yfinance) (0.0.10)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yfinance) (1.15.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.0.12)
Installing collected packages: requests, lxml, yfinance
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
  Attempting uninstall: lxml
    Found existing installation: lxml 4.2.6
    Uninstalling lxml-4.2.6:
      Successfully uninstalled lxml-4.2.6
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.27.1 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
Successfully installed lxml-4.8.0 requests-2.27.1 yfinance-0.1.70

In [ ]:
!pip install yahoo_fin

Collecting yahoo_fin
  Downloading yahoo_fin-0.8.9.1-py3-none-any.whl (10 kB)
Collecting requests-html
  Downloading requests_html-0.10.0-py3-none-any.whl (13 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from yahoo_fin) (1.3.5)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from yahoo_fin) (2.27.1)
Collecting feedparser
  Downloading feedparser-6.0.8-py3-none-any.whl (81 kB)
     |████████████████████████████████| 81 kB 7.2 MB/s
Collecting sgmllib3k
  Downloading sgmllib3k-1.0.0.tar.gz (5.8 kB)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->yahoo_fin) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->yahoo_fin) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas->yahoo_fin) (1.21.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->yahoo_fin) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->yahoo_fin) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.7/dist-packages (from requests->yahoo_fin) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->yahoo_fin) (1.24.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->yahoo_fin) (2.10)
Collecting parse
  Downloading parse-1.19.0.tar.gz (30 kB)
Collecting pyquery
  Downloading pyquery-1.4.3-py3-none-any.whl (22 kB)
Collecting fake-useragent
  Downloading fake-useragent-0.1.11.tar.gz (13 kB)
Collecting pyppeteer>=0.0.14
  Downloading pyppeteer-1.0.2-py3-none-any.whl (83 kB)
     |████████████████████████████████| 83 kB 1.6 MB/s
Collecting w3lib
  Downloading w3lib-1.22.0-py2.py3-none-any.whl (20 kB)
Requirement already satisfied: bs4 in /usr/local/lib/python3.7/dist-packages (from requests-html->yahoo_fin) (0.0.1)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.8-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 39.6 MB/s
Collecting pyee<9.0.0,>=8.1.0
  Downloading pyee-8.2.2-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: importlib-metadata>=1.4 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (4.11.2)
Requirement already satisfied: tqdm<5.0.0,>=4.42.1 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (4.63.0)
Collecting websockets<11.0,>=10.0
  Downloading websockets-10.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (111 kB)
     |████████████████████████████████| 111 kB 39.6 MB/s
Requirement already satisfied: appdirs<2.0.0,>=1.4.3 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (1.4.4)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=1.4->pyppeteer>=0.0.14->requests-html->yahoo_fin) (3.10.0.2)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=1.4->pyppeteer>=0.0.14->requests-html->yahoo_fin) (3.7.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from bs4->requests-html->yahoo_fin) (4.6.3)
Collecting cssselect>0.7.9
  Downloading cssselect-1.1.0-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: lxml>=2.1 in /usr/local/lib/python3.7/dist-packages (from pyquery->requests-html->yahoo_fin) (4.8.0)
Building wheels for collected packages: fake-useragent, parse, sgmllib3k
  Building wheel for fake-useragent (setup.py) ... done
  Created wheel for fake-useragent: filename=fake_useragent-0.1.11-py3-none-any.whl size=13502 sha256=d1e1c0cc271a04f08c4f29ff1ecb560ed8235b936d45d0ca002659f6af49f7aa
  Stored in directory: /root/.cache/pip/wheels/ed/f7/62/50ab6c9a0b5567267ab76a9daa9d06315704209b2c5d032031
  Building wheel for parse (setup.py) ... done
  Created wheel for parse: filename=parse-1.19.0-py3-none-any.whl size=24591 sha256=2d0dec04554cfc8eb8d4013434bdf49766343455c19e0adb633a89d14270e870
  Stored in directory: /root/.cache/pip/wheels/9c/aa/cc/f2228050ccb40f22144b073f15a2c84f11204f29fc0dce028e
  Building wheel for sgmllib3k (setup.py) ... done
  Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6066 sha256=b9e48dab68dcbc4f0e4793d67409cb9adc8fdc3cdfdafeb0fddd7cc3e3bb00d2
  Stored in directory: /root/.cache/pip/wheels/73/ad/a4/0dff4a6ef231fc0dfa12ffbac2a36cebfdddfe059f50e019aa
Successfully built fake-useragent parse sgmllib3k
Installing collected packages: websockets, urllib3, pyee, cssselect, w3lib, sgmllib3k, pyquery, pyppeteer, parse, fake-useragent, requests-html, feedparser, yahoo-fin
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.27.1 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
Successfully installed cssselect-1.1.0 fake-useragent-0.1.11 feedparser-6.0.8 parse-1.19.0 pyee-8.2.2 pyppeteer-1.0.2 pyquery-1.4.3 requests-html-0.10.0 sgmllib3k-1.0.0 urllib3-1.26.8 w3lib-1.22.0 websockets-10.2 yahoo-fin-0.8.9.1

In [ ]:
from yahoo_fin.stock_info import get_data
import yahoo_fin.stock_info as si
import pandas as pd

In [ ]:
csv_name = 'Banks_hist_stocks.csv'

In [ ]:
#change date range here, but keep 1day interval
start_date="01/25/2019"

In [ ]:
end_date="01/25/2022"

In [ ]:
interval = "1d"

In [ ]:
df_hist_stock_prices = pd.DataFrame(columns = ['ticker','open','high','low','close','adjclose','volume'])

In [ ]:

stocks = ['FRBA', 'CSTR', 'MSBI', 'RBB', 'SPFI', 'BFC', 'QCRH', 'BY', 'CBNK', 'CFB','MCBS','OBNK','PFBC','CUBI',
          'CCNE','AMNB','MOFG','FISI','AMAL','WTBA']

for ticker in stocks:
    ticker_df = si.get_data(ticker, start_date=start_date, end_date=end_date, interval=interval)
    df_hist_stock_prices = df_hist_stock_prices.append(ticker_df)

In [ ]:
df_hist_stock_prices

,ticker,open,high,low,close,adjclose,volume
2019-01-25,AIR,37.509998,37.520000,37.070000,37.209999,36.929859,86200
2019-01-28,AIR,36.840000,37.270000,36.529999,36.869999,36.592419,123500
2019-01-29,AIR,36.869999,37.259998,36.500000,36.540001,36.264904,149200
2019-01-30,AIR,36.860001,37.200001,36.099998,36.930000,36.651962,529500
2019-01-31,AIR,36.759998,37.919998,36.759998,37.680000,37.396320,389200
...,...,...,...,...,...,...,...
2022-01-18,VEC,46.770000,48.230000,46.465000,47.689999,47.689999,49900
2022-01-19,VEC,47.810001,48.750000,47.610001,48.040001,48.040001,36400
2022-01-20,VEC,48.340000,48.730000,47.160000,47.490002,47.490002,58700
2022-01-21,VEC,47.470001,47.950001,46.570000,46.650002,46.650002,57700
2022-01-24,VEC,46.139999,47.419998,45.980000,47.360001,47.360001,90400

In [ ]:
df_hist_stock_prices.index.name = 'Date'

In [ ]:
df_hist_stock_prices = df_hist_stock_prices.reset_index()

In [ ]:
df_hist_stock_prices.rename(columns={'ticker': 'Ticker', 'open': 'Open','high':'High','low':'Low','close' : 'Close',\
                                     'adjclose': 'Adj Close','volume': 'Volume'}
                            ,inplace=True)

In [ ]:
df_hist_stock_prices.reset_index(drop=True, inplace=True)

In [ ]:
df_hist_stock_prices

,Date,Ticker,Open,High,Low,Close,Adj Close,Volume
0,2019-01-25,AIR,37.509998,37.520000,37.070000,37.209999,36.929859,86200
1,2019-01-28,AIR,36.840000,37.270000,36.529999,36.869999,36.592419,123500
2,2019-01-29,AIR,36.869999,37.259998,36.500000,36.540001,36.264904,149200
3,2019-01-30,AIR,36.860001,37.200001,36.099998,36.930000,36.651962,529500
4,2019-01-31,AIR,36.759998,37.919998,36.759998,37.680000,37.396320,389200
...,...,...,...,...,...,...,...,...
15092,2022-01-18,VEC,46.770000,48.230000,46.465000,47.689999,47.689999,49900
15093,2022-01-19,VEC,47.810001,48.750000,47.610001,48.040001,48.040001,36400
15094,2022-01-20,VEC,48.340000,48.730000,47.160000,47.490002,47.490002,58700
15095,2022-01-21,VEC,47.470001,47.950001,46.570000,46.650002,46.650002,57700
15096,2022-01-24,VEC,46.139999,47.419998,45.980000,47.360001,47.360001,90400

In [ ]:
df_hist_stock_prices.to_csv(csv_name, index=False)